settings:
  components:
    - Starbase
  labels:
    - "Status: Triaged"
  # Adds a comment with the JIRA ID
  add_gh_comment: true
  # Reflect changes on JIRA
  sync_description: true
  # Comments are synced from Github to JIRA
  # Nothing goes from JIRA to Github
  sync_comments: true
  # epic_key: "MTC-296"
  jira_project_key: "CRAFT"
  status_mapping:
    opened: Triaged
    closed: done
  label_mapping:
    "Type: Bug": Bug
    "Type: Cleanup": Task
    "Type: Documentation": Task
    "Type: Enhancement": Task
    "Type: Invalid": Task
    "Type: Question": Spike
    "Type: Refactor": Task
    "Type: Research": Spike
