blank_issues_enabled: false
contact_links:
  - name: Report a runtime issue
    url: https://forum.snapcraft.io/c/snapd/5
    about: Issues running snaps
  - name: Snapcraft Forum
    url: https://forum.snapcraft.io/c/snapcraft/13
    about: Issues creating snaps
